###
post http://localhost:3000/user
Content-Type: application/json

{
    "id": 3,
    "name": "devDuo"
}

###

put http://localhost:3000/user
Content-Type: application/json

{
    "id":2,
    "name": "DevDUO"
}

###

delete http://localhost:3000/users
Content-Type: application/json

{
    "id": 2
}
